/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'status' : BookingStatus,
  'eventId' : IDL.Nat,
  'resourceId' : IDL.Nat,
  'isVendor' : IDL.Bool,
});
export const EventStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'ongoing' : IDL.Null,
});
export const Event = IDL.Record({
  'status' : EventStatus,
  'date' : IDL.Int,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'venueName' : IDL.Text,
});
export const Vendor = IDL.Record({
  'name' : IDL.Text,
  'contactEmail' : IDL.Text,
  'category' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const Venue = IDL.Record({
  'name' : IDL.Text,
  'capacity' : IDL.Nat,
  'location' : IDL.Text,
});
export const Stats = IDL.Record({
  'upcomingEvents' : IDL.Nat,
  'totalEvents' : IDL.Nat,
  'totalVenues' : IDL.Nat,
  'totalVendors' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createBooking' : IDL.Func([Booking], [IDL.Nat], []),
  'createEvent' : IDL.Func([Event], [IDL.Nat], []),
  'createVendor' : IDL.Func([Vendor], [IDL.Nat], []),
  'createVenue' : IDL.Func([Venue], [IDL.Nat], []),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'deleteVendor' : IDL.Func([IDL.Nat], [], []),
  'deleteVenue' : IDL.Func([IDL.Nat], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'getAllVenues' : IDL.Func([], [IDL.Vec(Venue)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
  'getBookingsForEvent' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
  'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getVendor' : IDL.Func([IDL.Nat], [Vendor], ['query']),
  'getVenue' : IDL.Func([IDL.Nat], [Venue], ['query']),
  'updateEvent' : IDL.Func([IDL.Nat, Event], [], []),
  'updateVendor' : IDL.Func([IDL.Nat, Vendor], [], []),
  'updateVenue' : IDL.Func([IDL.Nat, Venue], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'status' : BookingStatus,
    'eventId' : IDL.Nat,
    'resourceId' : IDL.Nat,
    'isVendor' : IDL.Bool,
  });
  const EventStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'ongoing' : IDL.Null,
  });
  const Event = IDL.Record({
    'status' : EventStatus,
    'date' : IDL.Int,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'venueName' : IDL.Text,
  });
  const Vendor = IDL.Record({
    'name' : IDL.Text,
    'contactEmail' : IDL.Text,
    'category' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const Venue = IDL.Record({
    'name' : IDL.Text,
    'capacity' : IDL.Nat,
    'location' : IDL.Text,
  });
  const Stats = IDL.Record({
    'upcomingEvents' : IDL.Nat,
    'totalEvents' : IDL.Nat,
    'totalVenues' : IDL.Nat,
    'totalVendors' : IDL.Nat,
  });
  
  return IDL.Service({
    'createBooking' : IDL.Func([Booking], [IDL.Nat], []),
    'createEvent' : IDL.Func([Event], [IDL.Nat], []),
    'createVendor' : IDL.Func([Vendor], [IDL.Nat], []),
    'createVenue' : IDL.Func([Venue], [IDL.Nat], []),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'deleteVendor' : IDL.Func([IDL.Nat], [], []),
    'deleteVenue' : IDL.Func([IDL.Nat], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'getAllVenues' : IDL.Func([], [IDL.Vec(Venue)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
    'getBookingsForEvent' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
    'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getVendor' : IDL.Func([IDL.Nat], [Vendor], ['query']),
    'getVenue' : IDL.Func([IDL.Nat], [Venue], ['query']),
    'updateEvent' : IDL.Func([IDL.Nat, Event], [], []),
    'updateVendor' : IDL.Func([IDL.Nat, Vendor], [], []),
    'updateVenue' : IDL.Func([IDL.Nat, Venue], [], []),
  });
};

export const init = ({ IDL }) => { return []; };