/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'status' : BookingStatus,
  'eventId' : bigint,
  'resourceId' : bigint,
  'isVendor' : boolean,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface Event {
  'status' : EventStatus,
  'date' : bigint,
  'name' : string,
  'description' : string,
  'venueName' : string,
}
export type EventStatus = { 'upcoming' : null } |
  { 'cancelled' : null } |
  { 'completed' : null } |
  { 'ongoing' : null };
export interface Stats {
  'upcomingEvents' : bigint,
  'totalEvents' : bigint,
  'totalVenues' : bigint,
  'totalVendors' : bigint,
}
export interface Vendor {
  'name' : string,
  'contactEmail' : string,
  'category' : string,
  'contactPhone' : string,
}
export interface Venue {
  'name' : string,
  'capacity' : bigint,
  'location' : string,
}
export interface _SERVICE {
  'createBooking' : ActorMethod<[Booking], bigint>,
  'createEvent' : ActorMethod<[Event], bigint>,
  'createVendor' : ActorMethod<[Vendor], bigint>,
  'createVenue' : ActorMethod<[Venue], bigint>,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'deleteVendor' : ActorMethod<[bigint], undefined>,
  'deleteVenue' : ActorMethod<[bigint], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllVendors' : ActorMethod<[], Array<Vendor>>,
  'getAllVenues' : ActorMethod<[], Array<Venue>>,
  'getBooking' : ActorMethod<[bigint], Booking>,
  'getBookingsForEvent' : ActorMethod<[bigint], Array<Booking>>,
  'getEvent' : ActorMethod<[bigint], Event>,
  'getStats' : ActorMethod<[], Stats>,
  'getVendor' : ActorMethod<[bigint], Vendor>,
  'getVenue' : ActorMethod<[bigint], Venue>,
  'updateEvent' : ActorMethod<[bigint, Event], undefined>,
  'updateVendor' : ActorMethod<[bigint, Vendor], undefined>,
  'updateVenue' : ActorMethod<[bigint, Venue], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];