/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Venue {
    name: string;
    capacity: bigint;
    location: string;
}
export interface Stats {
    upcomingEvents: bigint;
    totalEvents: bigint;
    totalVenues: bigint;
    totalVendors: bigint;
}
export interface Booking {
    status: BookingStatus;
    eventId: bigint;
    resourceId: bigint;
    isVendor: boolean;
}
export interface Event {
    status: EventStatus;
    date: bigint;
    name: string;
    description: string;
    venueName: string;
}
export interface Vendor {
    name: string;
    contactEmail: string;
    category: string;
    contactPhone: string;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum EventStatus {
    upcoming = "upcoming",
    cancelled = "cancelled",
    completed = "completed",
    ongoing = "ongoing"
}
export interface backendInterface {
    createBooking(booking: Booking): Promise<bigint>;
    createEvent(event: Event): Promise<bigint>;
    createVendor(vendor: Vendor): Promise<bigint>;
    createVenue(venue: Venue): Promise<bigint>;
    deleteEvent(id: bigint): Promise<void>;
    deleteVendor(id: bigint): Promise<void>;
    deleteVenue(id: bigint): Promise<void>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllEvents(): Promise<Array<Event>>;
    getAllVendors(): Promise<Array<Vendor>>;
    getAllVenues(): Promise<Array<Venue>>;
    getBooking(id: bigint): Promise<Booking>;
    getBookingsForEvent(eventId: bigint): Promise<Array<Booking>>;
    getEvent(id: bigint): Promise<Event>;
    getStats(): Promise<Stats>;
    getVendor(id: bigint): Promise<Vendor>;
    getVenue(id: bigint): Promise<Venue>;
    updateEvent(id: bigint, event: Event): Promise<void>;
    updateVendor(id: bigint, vendor: Vendor): Promise<void>;
    updateVenue(id: bigint, venue: Venue): Promise<void>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, Event as _Event, EventStatus as _EventStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createBooking(arg0: Booking): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_Booking_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_Booking_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createEvent(arg0: Event): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(to_candid_Event_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(to_candid_Event_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createVendor(arg0: Vendor): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVendor(arg0);
            return result;
        }
    }
    async createVenue(arg0: Venue): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createVenue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVenue(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteVendor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVendor(arg0);
            return result;
        }
    }
    async deleteVenue(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVenue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVenue(arg0);
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvents();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvents();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVendors(): Promise<Array<Vendor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVendors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVendors();
            return result;
        }
    }
    async getAllVenues(): Promise<Array<Venue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVenues();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVenues();
            return result;
        }
    }
    async getBooking(arg0: bigint): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_Booking_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_Booking_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsForEvent(arg0: bigint): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsForEvent(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsForEvent(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(arg0: bigint): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return from_candid_Event_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return from_candid_Event_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getVendor(arg0: bigint): Promise<Vendor> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendor(arg0);
            return result;
        }
    }
    async getVenue(arg0: bigint): Promise<Venue> {
        if (this.processError) {
            try {
                const result = await this.actor.getVenue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVenue(arg0);
            return result;
        }
    }
    async updateEvent(arg0: bigint, arg1: Event): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, to_candid_Event_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateVendor(arg0: bigint, arg1: Vendor): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVendor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVendor(arg0, arg1);
            return result;
        }
    }
    async updateVenue(arg0: bigint, arg1: Venue): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVenue(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVenue(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BookingStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_EventStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventStatus): EventStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _BookingStatus;
    eventId: bigint;
    resourceId: bigint;
    isVendor: boolean;
}): {
    status: BookingStatus;
    eventId: bigint;
    resourceId: bigint;
    isVendor: boolean;
} {
    return {
        status: from_candid_BookingStatus_n12(_uploadFile, _downloadFile, value.status),
        eventId: value.eventId,
        resourceId: value.resourceId,
        isVendor: value.isVendor
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _EventStatus;
    date: bigint;
    name: string;
    description: string;
    venueName: string;
}): {
    status: EventStatus;
    date: bigint;
    name: string;
    description: string;
    venueName: string;
} {
    return {
        status: from_candid_EventStatus_n17(_uploadFile, _downloadFile, value.status),
        date: value.date,
        name: value.name,
        description: value.description,
        venueName: value.venueName
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    ongoing: null;
}): EventStatus {
    return "upcoming" in value ? EventStatus.upcoming : "cancelled" in value ? EventStatus.cancelled : "completed" in value ? EventStatus.completed : "ongoing" in value ? EventStatus.ongoing : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n10(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Booking_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Booking): _Booking {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_EventStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventStatus): _EventStatus {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Event_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Event): _Event {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: BookingStatus;
    eventId: bigint;
    resourceId: bigint;
    isVendor: boolean;
}): {
    status: _BookingStatus;
    eventId: bigint;
    resourceId: bigint;
    isVendor: boolean;
} {
    return {
        status: to_candid_BookingStatus_n3(_uploadFile, _downloadFile, value.status),
        eventId: value.eventId,
        resourceId: value.resourceId,
        isVendor: value.isVendor
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: EventStatus;
    date: bigint;
    name: string;
    description: string;
    venueName: string;
}): {
    status: _EventStatus;
    date: bigint;
    name: string;
    description: string;
    venueName: string;
} {
    return {
        status: to_candid_EventStatus_n7(_uploadFile, _downloadFile, value.status),
        date: value.date,
        name: value.name,
        description: value.description,
        venueName: value.venueName
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventStatus): {
    upcoming: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    ongoing: null;
} {
    return value == EventStatus.upcoming ? {
        upcoming: null
    } : value == EventStatus.cancelled ? {
        cancelled: null
    } : value == EventStatus.completed ? {
        completed: null
    } : value == EventStatus.ongoing ? {
        ongoing: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
